### PR TITLE
Attach tax_rate to avatax response based on avatax

### PR DESCRIPTION
**Pull request by lkostrowski**
## Checklist

- [ ] I added changesets and [read good practices](/.changeset/README.md).

### CODE REVIEW

**Review by krzysztofzuraw — APPROVED** [review]

**Comment by lkostrowski** [comment]
@szczecha can you verify this agains plugin calculations?

**Comment by szczecha** [comment]
> @szczecha can you verify this agains plugin calculations?

@lkostrowski I created an order from checkout for the same products and shipped one with the App enabled second with the plugin. As you see in the screenshots below App incorrectly rounded tax rates. For both cases taxes were calculated with 8.875% rate
Screenshot 2024-05-31 at 12 11 03


App 
AvataxApp

Plugin
AvataxPlugin

**Comment by lkostrowski** [comment]
Thanks, it looks like we need some `* 100` multiply, I will check this

**Comment by lkostrowski** [comment]
@szczecha I found that SAleor expects integer value instead float (eg rate: 23 instead 0.23). I fixed this, now calculations should be good 👍

**Review by szczecha — APPROVED** [review]
image

**Review by krzysztofzuraw — APPROVED** [review]

**Pull request merged**
